cache:
  directories:
   - $HOME/.m2
language: java
jdk:
 - oraclejdk8
 install:
<<<<<<< HEAD
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
=======
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
>>>>>>> 36c43f5254d2b77ac9cbec2b90b6221d8ccf7d07
